export function SyntheticDataBanner() {
  return (
    <div className="bg-amber-100 text-amber-900 border-b border-amber-200 px-4 py-2 text-sm">
      <strong className="font-semibold">Demo with synthetic data.</strong>{" "}
      No real PHI, no real claims, no affiliation with any health plan or insurer.
      All data is generated by scripts in this repository.
    </div>
  );
}
